-- ai slop generated by trevor, kinda fire

local WIDTH, HEIGHT = 800, 600
local PLAYER_SIZE = 24
local CELL_SIZE = 60
local FIXED_XP = 20

function glua.init()
	glua.window.set_name("Glua survivors")
	glua.window.set_size(WIDTH, HEIGHT)
end

-- ==========================================
-- 1. UTILITIES & FONT
-- ==========================================
local FONT = {
	["0"]={7,5,5,5,7},["1"]={2,2,2,2,2},["2"]={7,1,7,4,7},["3"]={7,1,7,1,7},["4"]={5,5,7,1,1},
	["5"]={7,4,7,1,7},["6"]={7,4,7,5,7},["7"]={7,1,1,1,1},["8"]={7,5,7,5,7},["9"]={7,5,7,1,1},
	["A"]={2,5,7,5,5},["B"]={6,5,6,5,6},["C"]={7,4,4,4,7},["D"]={6,5,5,5,6},["E"]={7,4,6,4,7},
	["F"]={7,4,6,4,4},["G"]={3,4,5,5,3},["H"]={5,5,7,5,5},["I"]={7,2,2,2,7},["J"]={1,1,1,5,2},
	["K"]={5,5,6,5,5},["L"]={4,4,4,4,7},["M"]={5,7,5,5,5},["N"]={5,7,7,5,5},["O"]={2,5,5,5,2},
	["P"]={6,5,6,4,4},["Q"]={2,5,5,6,1},["R"]={6,5,6,5,5},["S"]={3,4,2,1,6},["T"]={7,2,2,2,2},
	["U"]={5,5,5,5,7},["V"]={5,5,5,5,2},["W"]={5,5,5,7,5},["X"]={5,5,2,5,5},["Y"]={5,5,2,2,2},
	["Z"]={7,1,2,4,7},["-"]={0,0,7,0,0},[":"]={0,2,0,2,0},["!"]={2,2,2,0,2},["?"]={2,5,1,0,2},
	[" "]={0,0,0,0,0}, ["."]={0,0,0,0,2}, ["%"]={5,2,2,1,5}, ["+"]={0,2,7,2,0}
}
function draw_text(str, x, y, s, r, g, b, a)
	glua.graphics.set_color(r or 1, g or 1, b or 1, a or 1)
	local rects = {}
	str = tostring(str):upper()
	for i = 1, #str do
		local d = FONT[str:sub(i,i)] or FONT["0"]
		for row = 1, 5 do for col = 1, 3 do
			if math.floor(d[row] / 2^(3-col)) % 2 == 1 then
				table.insert(rects, {x + (i-1)*4*s + (col-1)*s, y + (row-1)*s, s, s})
			end
		end end
	end
	glua.graphics.fill_rects(rects)
end
function dist(x1, y1, x2, y2) return math.sqrt((x2-x1)^2 + (y2-y1)^2) end

function get_env_at(cx, cy)
	local n = (cx * 73856093) ~ (cy * 19349663); n = math.abs(n) % 1000
	if n < 20 then return "TREE"
	elseif n < 30 then return "ROCK"
	elseif n < 35 then return "CRATE"
	elseif n < 38 then return "BARREL"
	elseif n < 42 then return "NEST"
	elseif n < 44 then return "SHRINE"
	elseif n < 55 then return "WATER"
	elseif n < 60 then return "LAVA"
	elseif n < 65 then return "ICE"
	elseif n < 250 then return "GRASS"
	end
	return "NONE"
end

-- ==========================================
-- 2. GAME STATE
-- ==========================================
local state = "INTRO"
local player = { 
	x=0, y=0, hp=100, max_hp=100, shield=0, max_shield=30, lvl=1, exp=0, 
	speed=270, armor=0, luck=1, facing_x=1, gold=0, rerolls=1, reroll_cost=5,
	fire_rate=0.45, fire_timer=0, bullet_count=1, pierce=1, crit=5,
	saws=0, lightning=0, lightning_cd=0, axe=false, axe_timer=0, mine=false, mine_timer=0, poison=false, poison_timer=0,
	pet=false, pet_timer=0, missile=false, missile_timer=0, flame=false, flame_timer=0, void=false, void_timer=0,
	wand=false, wand_timer=0, orb_shield=false, garlic=false, garlic_timer=0, daggers=false, dagger_timer=0,
	magnet=90, regen=0.1, dash_cd=0, dash_timer=0, i_frames=0,
	thorns=0, lifesteal=0, dodge=0, curse=1, area=1, knockback=1, projspeed=1, greed=1, recovery=1,
	revive=0, active_cd=0, active_max=10
}

-- Weather System State
local weather = { type="CLEAR", timer=0, flash=0, bolts={}, rain={}, splash={} }
for i=1,150 do table.insert(weather.rain, {x=math.random(WIDTH), y=math.random(HEIGHT), s=math.random(10,20)}) end

local enemies, bullets, enemy_bullets, gems, pickups, popups, splats, afterimages, mines, blackholes, meteors = {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}
local destroyed_crates, visited_merchants = {}, {}
local footprints, shockwaves = {}, {}
local perks = {}
local cam_x, cam_y, shake, kills, time, wave, day_cycle = 0, 0, 0, 0, 0, 1, 0
local spawn_timer, combo, combo_timer, freeze_timer, intro_timer, tutorial_alpha = 0, 0, 0, 0, 2.0, 5.0
local dps_counter, dps_timer, slow_mo_timer = 0, 0, 0
local blood_moon, hard_mode, auto_aim, killer_name = false, false, true, ""

-- Audio
local SOUNDS = { SHOOT={}, HIT={}, GEM={}, BOOM={}, LEVEL={}, CRIT={}, RAIN={} }
for i=1,1000 do table.insert(SOUNDS.SHOOT, math.sin(i*0.5)*(1-i/1000)) end
for i=1,500 do table.insert(SOUNDS.HIT, (math.random()*2-1)*(1-i/500)) end
for i=1,3000 do table.insert(SOUNDS.GEM, math.sin(i*0.2)*(1-i/3000)) end
for i=1,8000 do table.insert(SOUNDS.BOOM, (math.random()*2-1)*(1-i/5000)) end
for i=1,8000 do table.insert(SOUNDS.LEVEL, math.sin(i*(0.1+math.floor(i/2000)*0.05))*(1-i/8000)) end
for i=1,1000 do table.insert(SOUNDS.CRIT, math.sin(i*0.8)*(1-i/1000)) end
for i=1,2000 do table.insert(SOUNDS.RAIN, (math.random()*0.2-0.1)) end -- White noise
function play_snd(k) if SOUNDS[k] then glua.audio.play_samples(SOUNDS[k]) end end

-- 3. PERKS
function generate_perks()
	local pool = {
		{id="SPEED",n="SPEED"}, {id="FIRE",n="FIRE RATE"}, {id="DMG",n="PIERCE"},
		{id="SAW",n="SAWBLADE"}, {id="ZAP",n="LIGHTNING"}, {id="AXE",n="AXE"},
		{id="MINE",n="MINES"}, {id="POISON",n="POISON"}, {id="HP",n="MAX HP"},
		{id="ARMOR",n="ARMOR"}, {id="SHIELD",n="SHIELD"}, {id="MAGNET",n="MAGNET"}, {id="LUCK",n="LUCK"},
		{id="PET",n="DRONE"}, {id="MISSILE",n="MISSILES"}, {id="FLAME",n="FLAMETHROWER"}, {id="VOID",n="BLACK HOLE"},
		{id="WAND",n="MAGIC WAND"}, {id="ORB",n="ORBIT SHIELD"}, {id="GARLIC",n="GARLIC AURA"}, {id="DAGGER",n="DAGGERS"},
		{id="THORN",n="THORNS"}, {id="LIFE",n="LIFE STEAL"}, {id="DODGE",n="DODGE"}, {id="AREA",n="AREA SIZE"},
		{id="KB",n="KNOCKBACK"}, {id="CURSE",n="CURSE"}, {id="REVIVE",n="EXTRA LIFE"},
		{id="GREED",n="GREED"}, {id="RECOV",n="RECOVERY"}
	}
	perks = {}
	for i=1,3 do
		local p = pool[math.random(#pool)]
		local r = math.random(100); local r_t, r_c = "COMMON", {1,1,1}
		if r>92 then r_t,r_c="LEGEND",{1,0.8,0} elseif r>75 then r_t,r_c="RARE",{0.3,0.3,1} end
		table.insert(perks, {id=p.id, n=p.n, r=r_t, c=r_c})
	end
	state = "LEVELUP"
	play_snd("LEVEL")
end

function apply_perk(idx)
	local p = perks[idx]; local m = (p.r=="LEGEND" and 2) or (p.r=="RARE" and 1.5) or 1
	if p.id=="SPEED" then player.speed=player.speed+(30*m)
	elseif p.id=="FIRE" then player.fire_rate=player.fire_rate*(1-(0.1*m))
	elseif p.id=="DMG" then player.pierce=player.pierce+1; player.crit=player.crit+(5*m)
	elseif p.id=="SAW" then player.saws=player.saws+1
	elseif p.id=="ZAP" then player.lightning=player.lightning+1
	elseif p.id=="AXE" then player.axe=true
	elseif p.id=="MINE" then player.mine=true
	elseif p.id=="POISON" then player.poison=true
	elseif p.id=="PET" then player.pet=true
	elseif p.id=="MISSILE" then player.missile=true
	elseif p.id=="FLAME" then player.flame=true
	elseif p.id=="VOID" then player.void=true
	elseif p.id=="WAND" then player.wand=true
	elseif p.id=="ORB" then player.orb_shield=true
	elseif p.id=="GARLIC" then player.garlic=true
	elseif p.id=="DAGGER" then player.daggers=true
	elseif p.id=="HP" then player.max_hp=player.max_hp+(25*m); player.hp=player.hp+25
	elseif p.id=="ARMOR" then player.armor=player.armor+(1*m)
	elseif p.id=="SHIELD" then player.max_shield=player.max_shield+(15*m)
	elseif p.id=="MAGNET" then player.magnet=player.magnet+(50*m)
	elseif p.id=="LUCK" then player.luck=player.luck+(1*m) 
	elseif p.id=="THORN" then player.thorns=player.thorns+(2*m)
	elseif p.id=="LIFE" then player.lifesteal=player.lifesteal+(5*m)
	elseif p.id=="DODGE" then player.dodge=player.dodge+(5*m)
	elseif p.id=="AREA" then player.area=player.area+(0.2*m)
	elseif p.id=="KB" then player.knockback=player.knockback+(0.5*m)
	elseif p.id=="CURSE" then player.curse=player.curse+(0.5*m)
	elseif p.id=="REVIVE" then player.revive=player.revive+1 
	elseif p.id=="GREED" then player.greed=player.greed+(0.5*m)
	elseif p.id=="RECOV" then player.recovery=player.recovery+(0.5*m) end
	
	table.insert(shockwaves, {x=player.x, y=player.y, r=10, max_r=400, life=0.5})
	for _,e in ipairs(enemies) do 
		local d = dist(player.x,player.y,e.x,e.y)
		e.x = e.x + (e.x-player.x)/d * 200; e.y = e.y + (e.y-player.y)/d * 200
	end
	state = "PLAY"
end

function add_popup(x, y, txt, col, size)
	table.insert(popups, {x=x, y=y, txt=txt, col=col, life=1.0, max_life=1.0, vy=-180, size=size or 2})
end

function spawn_particle(x, y, c)
	for i=1,5 do table.insert(popups, {x=x, y=y, txt=".", col=c, life=0.4, max_life=0.4, vy=(math.random()-0.5)*300, size=1}) end
end

-- 4. LOGIC
function check_env_collision(x, y, r, is_ghost)
	if is_ghost then return false end
	local cx, cy = math.floor(x/CELL_SIZE), math.floor(y/CELL_SIZE)
	for ox=-1,1 do for oy=-1,1 do
		local t = get_env_at(cx+ox, cy+oy)
		if (t == "TREE" or t == "ROCK" or (t == "CRATE" and not destroyed_crates[(cx+ox)..","..(cy+oy)]) or (t=="BARREL" and not destroyed_crates[(cx+ox)..","..(cy+oy)])) then
			local obj_x, obj_y = (cx+ox)*CELL_SIZE + CELL_SIZE/2, (cy+oy)*CELL_SIZE + CELL_SIZE/2
			if dist(x, y, obj_x, obj_y) < (r + 15) then return true end
		end
	end end
	return false
end

function update(dt)
	if state == "INTRO" then
		intro_timer = intro_timer - dt
		if glua.keyboard.is_pressed("h") then hard_mode = true end
		if intro_timer < 0 then state = "PLAY" end
		return
	end
	if state ~= "PLAY" then return end
	
	time = time + dt; wave = math.floor(time/60)+1
	day_cycle = math.sin(time/20)
	
	local enemy_dt = dt
	if slow_mo_timer > 0 then slow_mo_timer = slow_mo_timer - dt; enemy_dt = dt * 0.2 end
	
	dps_timer = dps_timer + dt; if dps_timer > 1 then dps_counter = 0; dps_timer = 0 end
	freeze_timer = math.max(0, freeze_timer - dt)
	combo_timer = combo_timer - dt; if combo_timer < 0 then combo = 0 end
	player.active_cd = math.max(0, player.active_cd - dt)
	tutorial_alpha = math.max(0, tutorial_alpha - dt)
	blood_moon = (time % 300 > 270)

	-- WEATHER SYSTEM (FIXED)
	weather.timer = weather.timer + dt
	if weather.timer > 30 then
		weather.type = (math.random() < 0.3 and "CLEAR" or (math.random() < 0.7 and "RAIN" or "STORM"))
		weather.timer = 0
		if weather.type ~= "STORM" then weather.bolts = {}; weather.flash = 0 end -- Instant Cleanup
	end
	
	-- Update Bolts (Always run, independent of current weather)
	for i=#weather.bolts, 1, -1 do
		weather.bolts[i].life = weather.bolts[i].life - dt
		if weather.bolts[i].life < 0 then table.remove(weather.bolts, i) end
	end
	weather.flash = math.max(0, weather.flash - dt * 2)
	
	-- New Lightning Spawn
	if weather.type == "STORM" and math.random(math.ceil(1/dt)) == 1 then
		weather.flash = 0.4; shake = 8; play_snd("BOOM")
		local sx = math.random(WIDTH); local sy = math.random(0, 100)
		local segs = {}; local cx, cy = sx, sy
		for k=1,8 do
			local nx, ny = cx+math.random(-30,30), cy+math.random(40,90)
			table.insert(segs, {x1=cx, y1=cy, x2=nx, y2=ny})
			cx, cy = nx, ny
		end
		table.insert(weather.bolts, {segs=segs, life=0.2})
	end
	-- Rain Noise
	if (weather.type=="RAIN" or weather.type=="STORM") and math.random(20)==1 then play_snd("RAIN") end
	
	if math.random(math.ceil(5/dt)) == 1 then table.insert(meteors, {x=player.x+math.random(-300,300), y=player.y+math.random(-300,300), timer=2.0}) end
	for i=#meteors,1,-1 do
		local m = meteors[i]; m.timer = m.timer - dt
		if m.timer < 0 then
			shake = 10; table.insert(shockwaves, {x=m.x, y=m.y, r=10, max_r=100, life=0.5})
			play_snd("BOOM")
			for j=#enemies,1,-1 do if dist(enemies[j].x, enemies[j].y, m.x, m.y) < 80 then damage_enemy(enemies[j], 100, "METEOR") end end
			table.remove(meteors, i)
		end
	end
	
	if freeze_timer > 0 then enemy_dt = 0 end

	-- Player
	player.dash_cd = player.dash_cd - dt
	player.i_frames = player.i_frames - dt
	player.hp = math.min(player.max_hp * 1.5, player.hp + player.regen * dt)
	if player.hp > player.max_hp then player.shield = math.min(player.max_shield, player.shield + dt) end

	local vx, vy = 0, 0
	if glua.keyboard.is_pressed("up") then vy = -1 end
	if glua.keyboard.is_pressed("down") then vy = 1 end
	if glua.keyboard.is_pressed("left") then vx = -1 end
	if glua.keyboard.is_pressed("right") then vx = 1 end
	
	local speed = player.speed * (player.dash_timer > 0 and 3 or 1)
	if combo > 20 then speed = speed * 1.2 end
	
	local cx, cy = math.floor(player.x/CELL_SIZE), math.floor(player.y/CELL_SIZE)
	local env = get_env_at(cx, cy)
	if env == "WATER" and player.dash_timer <= 0 then speed = speed * 0.7 
	elseif env == "ICE" then speed = speed * 1.3 
	elseif env == "LAVA" and player.dash_timer <= 0 then take_damage(30 * dt) end

	if player.dash_timer > 0 then 
		table.insert(afterimages, {x=player.x, y=player.y, life=0.4})
		player.dash_timer = player.dash_timer - dt
		table.insert(bullets, {x=player.x, y=player.y, vx=0, vy=0, type="FLAME", life=0.5, pierce=99, hit={}}) 
	end
	
	if vx~=0 or vy~=0 then
		local m = math.sqrt(vx*vx+vy*vy)
		local nx, ny = player.x + (vx/m)*speed*dt, player.y + (vy/m)*speed*dt
		if not check_env_collision(nx, player.y, 8) then player.x = nx end
		if not check_env_collision(player.x, ny, 8) then player.y = ny end
		if vx ~= 0 then player.facing_x = vx end
		if math.random(math.ceil(0.2/dt))==1 then table.insert(footprints, {x=player.x, y=player.y+10, life=2.0}) end
	end
	
	if env == "SHRINE" then
		add_popup(player.x, player.y, "RAMPAGE!", {1,0,0}, 4)
		player.fire_rate = player.fire_rate * 0.5; destroyed_crates[cx..","..cy] = true
	end
	if math.random(math.ceil(20/dt))==1 and not visited_merchants[wave] then
		table.insert(pickups, {x=player.x+200, y=player.y, type="MERCHANT"}); visited_merchants[wave] = true
	end
	
	shake = shake * (0.1 ^ dt)
	cam_x = player.x - WIDTH/2 + (math.random()-0.5)*shake
	cam_y = player.y - HEIGHT/2 + (math.random()-0.5)*shake

	-- WEAPONS
	player.fire_timer = player.fire_timer + dt
	if player.fire_timer >= player.fire_rate then
		local t = nil; local min_d = 700
		local mode = auto_aim and "NEAREST" or "FACING"
		if mode == "NEAREST" then for _,e in ipairs(enemies) do local d=dist(player.x,player.y,e.x,e.y); if d<min_d then min_d=d; t=e end end end
		
		local ang = 0
		if t then ang = math.atan2(t.y-player.y, t.x-player.x)
		else ang = math.atan2(0, player.facing_x) end
		
		-- Muzzle Flash
		table.insert(shockwaves, {x=player.x+math.cos(ang)*20, y=player.y+math.sin(ang)*20, r=5, max_r=15, life=0.1})
		play_snd("SHOOT")
		
		for i=1,player.bullet_count do
			local a = ang + (i-(player.bullet_count+1)/2)*0.2
			table.insert(bullets, {x=player.x, y=player.y, vx=math.cos(a)*700*player.projspeed, vy=math.sin(a)*700*player.projspeed, type="BULLET", life=1.5, pierce=player.pierce, hit={}})
		end
		player.fire_timer = 0
	end
	
	if player.axe then
		player.axe_timer = player.axe_timer + dt
		if player.axe_timer > 1.2 then table.insert(bullets, {x=player.x, y=player.y, vx=0, vy=-700, type="AXE", life=2.0, pierce=999, hit={}}); player.axe_timer = 0 end
	end
	if player.mine then
		player.mine_timer = player.mine_timer + dt
		if player.mine_timer > 2.5 then table.insert(mines, {x=player.x, y=player.y}); player.mine_timer = 0 end
	end
	if player.poison then
		player.poison_timer = player.poison_timer + dt
		if player.poison_timer > 0.3 then table.insert(bullets, {x=player.x, y=player.y, vx=0, vy=0, type="POISON", life=3.0, pierce=999, hit={}}); player.poison_timer = 0 end
	end
	if player.missile then
		player.missile_timer = player.missile_timer + dt
		if player.missile_timer > 1.5 then table.insert(bullets, {x=player.x, y=player.y, vx=0, vy=-300, type="MISSILE", life=3.0, pierce=1, hit={}, target=nil}); player.missile_timer = 0 end
	end
	if player.flame then
		player.flame_timer = player.flame_timer + dt
		if player.flame_timer > 0.1 then
			local a = math.atan2(0, player.facing_x) + (math.random()-0.5)*0.5
			table.insert(bullets, {x=player.x, y=player.y, vx=math.cos(a)*500, vy=math.sin(a)*500, type="FLAME", life=0.6, pierce=5, hit={}}); player.flame_timer = 0
		end
	end
	if player.void then
		player.void_timer = player.void_timer + dt
		if player.void_timer > 5.0 then table.insert(blackholes, {x=player.x, y=player.y, life=3.0}); player.void_timer = 0 end
	end
	if player.pet then
		player.pet_timer = player.pet_timer + dt
		if player.pet_timer > math.max(0.2, 1.0 - player.lvl*0.05) then -- Pet Evolves
			table.insert(bullets, {x=player.x+math.cos(time)*40, y=player.y+math.sin(time)*40, vx=player.facing_x*600, vy=0, type="PETLASER", life=1.0, pierce=1, hit={}}); player.pet_timer = 0 
		end
	end
	if player.wand then
		player.wand_timer = player.wand_timer + dt
		if player.wand_timer > 0.8 then
			local t, md = nil, 400; for _,e in ipairs(enemies) do local d=dist(player.x,player.y,e.x,e.y); if d<md then md=d; t=e end end
			if t then damage_enemy(t, 8, "WAND"); spawn_particle(t.x, t.y, {0,1,1}); player.wand_timer = 0 end
		end
	end
	if player.daggers then
		player.dagger_timer = player.dagger_timer + dt
		if player.dagger_timer > 1.0 then
			table.insert(bullets, {x=player.x, y=player.y, vx=player.facing_x*900, vy=0, type="DAGGER", life=1.0, pierce=2, hit={}}); player.dagger_timer = 0
		end
	end
	if player.garlic then
		player.garlic_timer = player.garlic_timer + dt
		if player.garlic_timer > 0.5 then
			for _,e in ipairs(enemies) do if dist(player.x,player.y,e.x,e.y) < 80 then damage_enemy(e, 2, "GARLIC") end end
			player.garlic_timer = 0
		end
	end

	if player.lightning > 0 then
		player.lightning_cd = player.lightning_cd - dt
		if player.lightning_cd <= 0 then
			local t_list={}; for _,e in ipairs(enemies) do if dist(player.x,player.y,e.x,e.y)<400 then table.insert(t_list,e) end end
			if #t_list > 0 then
				local start = t_list[math.random(#t_list)]; damage_enemy(start, 5, "ZAP")
				local curr, chain = start, player.lightning
				while chain > 0 do
					local next_t, min_d = nil, 300
					for _,e in ipairs(enemies) do if e ~= curr and dist(curr.x,curr.y,e.x,e.y)<min_d then min_d=dist(curr.x,curr.y,e.x,e.y); next_t=e end end
					if next_t then
						damage_enemy(next_t, 5, "ZAP"); curr = next_t; chain = chain - 1
					else break end
				end
				player.lightning_cd = 1.5
			end
		end
	end

	-- Spawn Enemies
	spawn_timer = spawn_timer + dt
	local spawn_rate = math.max(0.05, 0.6-(wave*0.05)) / player.curse
	if blood_moon or hard_mode then spawn_rate = spawn_rate / 2 end
	
	if spawn_timer > spawn_rate then
		local a = math.random()*6.28; local d_spawn = 600
		local type = "NORMAL"
		if wave>2 and math.random(5)==1 then type="SHOOTER" end
		if wave>1 and math.random(6)==1 then type="SWARMER" end
		if wave>3 and math.random(10)==1 then type="BOMBER" end
		if wave>4 and math.random(20)==1 then type="HEALER" end
		if wave>5 and math.random(30)==1 then type="SPLITTER" end
		if wave>6 and math.random(50)==1 then type="INVISIBLE" end
		if wave>2 and math.random(40)==1 then type="TELEPORT" end
		if wave>3 and math.random(40)==1 then type="CHARGER" end
		if wave>4 and math.random(50)==1 then type="TURRET" end
		if wave>5 and math.random(60)==1 then type="GHOST" end
		if wave>3 and math.random(60)==1 then type="SLIME" end
		
		local boss = (time%60<1.5) and (time>10)
		if time > 600 then boss = true end
		local elite = not boss and math.random(20) == 1
		
		local function spawn(t, x, y)
			local hp = (boss and 300 or (t=="SHOOTER" and 6 or 4)) * (elite and 3 or 1)
			table.insert(enemies, {
				x=x, y=y,
				hp=hp, max_hp=hp,
				speed=(boss and 90 or (t=="BOMBER" and 210 or t=="CHARGER" and 300 or t=="TURRET" and 0 or t=="GHOST" and 80 or 132)) * (blood_moon and 2 or 1),
				type=t, boss=boss, elite=elite, shoot_cd=2, flash=0, teleport_cd=3,
				shield=math.random(10)==1,
				poison_cd=0, squash=1 -- Squash Effect
			})
		end
		
		if type == "SWARMER" then
			for k=1,4 do spawn("SWARMER", player.x+math.cos(a)*d_spawn+math.random(40), player.y+math.sin(a)*d_spawn) end
		elseif type == "AMBUSH" or (wave==5 and math.random(100)==1) then
			for k=1,12 do spawn("NORMAL", player.x+math.cos(k)*300, player.y+math.sin(k)*300) end
			add_popup(player.x, player.y, "HORDE!", {1,0,0}, 4)
		else
			spawn(type, player.x+math.cos(a)*d_spawn, player.y+math.sin(a)*d_spawn)
		end
		spawn_timer = 0
	end
	
	local px_cell, py_cell = math.floor(player.x/CELL_SIZE), math.floor(player.y/CELL_SIZE)
	if get_env_at(px_cell, py_cell) == "NEST" and math.random(math.ceil(1/dt))==1 then
		table.insert(enemies, {x=px_cell*CELL_SIZE, y=py_cell*CELL_SIZE, hp=2, max_hp=2, speed=180, type="SWARMER", flash=0, squash=1})
	end

	-- Update Enemies
	for i=#enemies,1,-1 do
		local e = enemies[i]
		local d = dist(e.x,e.y,player.x,player.y)
		e.squash = e.squash + (1 - e.squash) * dt * 5 -- Recover squash
		
		-- Smart Despawn
		if d > 1200 then table.remove(enemies, i); goto continue end
		
		for _,bh in ipairs(blackholes) do if dist(e.x,e.y,bh.x,bh.y)<150 then e.x=e.x+(bh.x-e.x)*3*dt; e.y=e.y+(bh.y-e.y)*3*dt end end
		
		local can_move = true
		if e.type == "BOMBER" and d < 40 then take_damage(20); e.hp = 0
		elseif (e.type == "SHOOTER" or e.type == "TURRET") and d < 500 then
			e.shoot_cd = e.shoot_cd - enemy_dt
			if e.shoot_cd <= 0 then
				local a = math.atan2(player.y-e.y, player.x-e.x)
				table.insert(enemy_bullets, {x=e.x, y=e.y, vx=math.cos(a)*300, vy=math.sin(a)*300})
				e.shoot_cd = 3
			end
			if e.type == "TURRET" then can_move = false end
		elseif e.type == "TELEPORT" and d > 100 then
			e.teleport_cd = e.teleport_cd - enemy_dt
			if e.teleport_cd <= 0 then e.x=player.x+math.random(-100,100); e.y=player.y+math.random(-100,100); e.teleport_cd=4 end
		elseif e.type == "HEALER" then
			for _, ally in ipairs(enemies) do 
				local m = ally.max_hp or ally.hp or 1
				if ally ~= e and ally.hp < m and dist(e.x,e.y,ally.x,ally.y)<100 then ally.hp=ally.hp+6*dt end 
			end
			local nx, ny = e.x+(player.x-e.x)/d*e.speed*0.8*enemy_dt, e.y+(player.y-e.y)/d*e.speed*0.8*enemy_dt
			if not check_env_collision(nx, e.y, 10) then e.x=nx end
			if not check_env_collision(e.x, ny, 10) then e.y=ny end
		end
		
		if can_move and e.type ~= "HEALER" then
			local spd = e.speed
			if e.type == "CHARGER" and d < 300 then spd = spd * 2 end
			local nx, ny = e.x+(player.x-e.x)/d*spd*enemy_dt, e.y+(player.y-e.y)/d*spd*enemy_dt
			if not check_env_collision(nx, e.y, 10, e.type=="GHOST") then e.x=nx end
			if not check_env_collision(e.x, ny, 10, e.type=="GHOST") then e.y=ny end
		end
		
		if e.elite or e.type == "SLIME" then
			e.poison_cd = e.poison_cd + enemy_dt
			if e.poison_cd > 1 then table.insert(mines, {x=e.x, y=e.y, enemy=true, life=5}); e.poison_cd=0 end
		end
		
		if e.boss and math.random(math.ceil(5/dt))==1 then
			table.insert(enemies, {x=e.x, y=e.y, hp=4, max_hp=4, speed=210, type="SWARMER", flash=0, squash=1})
		end
		
		e.flash = e.flash - dt
		if d < 25 and player.thorns > 0 and e.flash <= 0 then damage_enemy(e, player.thorns, "THORNS") end
		
		if d < (e.boss and 40 or 20) then
			if player.orb_shield then damage_enemy(e, 5, "ORB"); e.x=e.x-(player.x-e.x)*10*dt; e.y=e.y-(player.y-e.y)*10*dt
			elseif player.i_frames <= 0 then
				if math.random(100) < player.dodge then add_popup(player.x, player.y, "MISS", {1,1,1}, 2)
				else take_damage(10, e) end
			end
		end
		if e.hp <= 0 then kill_enemy(i) end
		
		::continue::
	end
	
	for i=#mines,1,-1 do
		local m = mines[i]
		if m.enemy then
			m.life = m.life - dt; if m.life < 0 then table.remove(mines, i) end
			if dist(m.x,m.y,player.x,player.y)<20 then take_damage(1) end
		else
			for j=#enemies,1,-1 do
				if dist(m.x, m.y, enemies[j].x, enemies[j].y) < 30 * player.area then
					damage_enemy(enemies[j], 20, "MINE"); table.remove(mines, i)
					play_snd("BOOM")
					table.insert(shockwaves, {x=m.x, y=m.y, r=10, max_r=50, life=0.3})
					break
				end
			end
		end
	end
	
	for i=#blackholes,1,-1 do
		local b = blackholes[i]; b.life = b.life - dt
		if b.life < 0 then table.remove(blackholes,i) end
	end

	for i=#enemy_bullets,1,-1 do
		local b = enemy_bullets[i]; b.x=b.x+b.vx*enemy_dt; b.y=b.y+b.vy*enemy_dt
		if dist(b.x,b.y,player.x,player.y)<15 and player.i_frames<=0 then take_damage(5); table.remove(enemy_bullets,i) end
		if dist(b.x,b.y,player.x,player.y)>900 then table.remove(enemy_bullets,i) end
	end

	for i=#bullets,1,-1 do
		local b = bullets[i]
		if b.type == "AXE" then b.vy=b.vy+18*dt; b.x=b.x+(player.facing_x*180*dt) end
		if b.type == "MISSILE" then
			if not b.target or b.target.hp <= 0 then
				local min_d = 400; for _, e in ipairs(enemies) do local d=dist(b.x,b.y,e.x,e.y); if d<min_d then min_d=d; b.target=e end end
			end
			if b.target then
				local angle = math.atan2(b.target.y-b.y, b.target.x-b.x)
				b.vx = b.vx*0.95 + math.cos(angle)*60
				b.vy = b.vy*0.95 + math.sin(angle)*60
			end
		end
		
		b.x=b.x+b.vx*dt; b.y=b.y+b.vy*dt; b.life=b.life-dt
		
		for j,e in ipairs(enemies) do
			local rad = (b.type=="POISON" and 40 or 25) * player.area
			if not b.hit[e] and dist(b.x,b.y,e.x,e.y) < rad then
				damage_enemy(e, (b.type=="AXE" and 6 or (b.type=="DAGGER" and 5 or 3)), "GUN")
				if b.type ~= "POISON" and b.type ~= "FLAME" then 
					b.hit[e]=true; b.pierce=b.pierce-1
					local kb = player.knockback * 10
					local a = math.atan2(e.y-b.y, e.x-b.x); e.x=e.x+math.cos(a)*kb; e.y=e.y+math.sin(a)*kb
				end
				if b.pierce<=0 then break end
			end
		end
		
		local cx, cy = math.floor(b.x/CELL_SIZE), math.floor(b.y/CELL_SIZE)
		local t = get_env_at(cx, cy)
		if (t=="CRATE" or t=="BARREL") and not destroyed_crates[cx..","..cy] then
			destroyed_crates[cx..","..cy] = true
			add_popup(cx*CELL_SIZE, cy*CELL_SIZE, "CRUSH", {1,0.5,0}, 2)
			spawn_particle(cx*CELL_SIZE+30, cy*CELL_SIZE+30, {0.6,0.4,0.2})
			if t=="BARREL" then 
				table.insert(shockwaves, {x=cx*CELL_SIZE, y=cy*CELL_SIZE, r=10, max_r=100, life=0.5})
				play_snd("BOOM")
				for _,e in ipairs(enemies) do if dist(e.x,e.y,cx*CELL_SIZE,cy*CELL_SIZE)<100 then damage_enemy(e,50,"BARREL") end end
			else
				table.insert(gems, {x=cx*CELL_SIZE+30, y=cy*CELL_SIZE+30, val=5, col={0,1,0}, sz=10})
			end
			b.pierce = 0
		end
		
		if check_env_collision(b.x, b.y, 2) and b.type=="BULLET" then b.pierce = 0 end
		if b.life<0 or b.pierce<=0 then table.remove(bullets, i) end
	end
	
	-- Gems & Fusion
	for i=1,#gems do
		for j=i+1,#gems do
			if gems[i].val < 100 and gems[j].val < 100 and dist(gems[i].x,gems[i].y,gems[j].x,gems[j].y) < 20 then
				gems[i].val = gems[i].val + gems[j].val
				gems[i].sz = math.min(20, gems[i].sz + 2)
				gems[i].col = {1, 0, 0}
				table.remove(gems, j)
				break
			end
		end
	end

	for i=#gems,1,-1 do
		local g = gems[i]; local d = dist(g.x,g.y,player.x,player.y)
		-- Gold also magnets now
		if d < player.magnet then
			local pull = 15 * (1 - d/player.magnet); g.x=g.x+(player.x-g.x)/d*pull*60*dt; g.y=g.y+(player.y-g.y)/d*pull*60*dt
			if math.random(math.ceil(0.1/dt))==1 then spawn_particle(g.x, g.y, g.col) end
		end
		if d < 20 then
			play_snd("GEM")
			player.exp=player.exp+g.val; table.remove(gems,i)
			if player.exp>=FIXED_XP then player.exp=0; player.lvl=player.lvl+1; generate_perks() end
		end
	end
	
	for i=#pickups,1,-1 do
		local p = pickups[i]; if dist(p.x,p.y,player.x,player.y)<30 then
			play_snd("GEM")
			if p.type=="MEDKIT" then player.hp=math.min(player.max_hp,player.hp+(30*player.recovery)); add_popup(player.x,player.y,"HEAL",{0,1,0})
			elseif p.type=="NUKE" then enemies={}; enemy_bullets={}; weather.flash=1; shake=20; play_snd("BOOM")
			elseif p.type=="FREEZE" then freeze_timer=4.0
			elseif p.type=="VACUUM" then for _,g in ipairs(gems) do g.x=player.x; g.y=player.y end 
			elseif p.type=="CHILLI" then player.speed=player.speed+100; player.flame=true 
			elseif p.type=="MAGNET" then player.magnet=player.magnet+200
			elseif p.type=="MERCHANT" then
				if player.gold >= 10 then player.gold=player.gold-10; player.hp=player.max_hp; add_popup(player.x,player.y,"FULL HEAL",{1,1,0})
				else add_popup(player.x,player.y,"NEED 10G",{1,0,0}) end
			elseif p.type=="CHEST" then player.gold=player.gold+20; player.exp=player.exp+50; add_popup(player.x,player.y,"TREASURE!",{1,0.8,0},3)
			elseif p.type=="CURSED" then player.max_hp=player.max_hp/2; player.curse=player.curse+1; add_popup(player.x,player.y,"CURSED...",{0.5,0,0.5},3)
			end
			table.remove(pickups,i)
		end
	end
	
	for i=#popups,1,-1 do
		local p = popups[i]; p.vy=p.vy+100*dt; p.x=p.x+(math.random()-0.5); p.y=p.y+p.vy*dt; p.life=p.life-dt
		if p.life<0 then table.remove(popups,i) end
	end
	for i=#shockwaves,1,-1 do
		local s = shockwaves[i]; s.r=s.r+dt*200; s.life=s.life-dt
		if s.life<0 then table.remove(shockwaves,i) end
	end
	
	-- Splash Logic
	if weather.type=="RAIN" or weather.type=="STORM" then
		for _,r in ipairs(weather.rain) do
			if r.y > HEIGHT-10 and math.random(10)==1 then
				table.insert(weather.splash, {x=r.x, y=HEIGHT, life=0.2})
			end
		end
	end
	for i=#weather.splash,1,-1 do
		weather.splash[i].life = weather.splash[i].life - dt
		if weather.splash[i].life < 0 then table.remove(weather.splash, i) end
	end
end

function damage_enemy(e, amt, src)
	if e.shield then e.shield=false; amt=amt*0.2; add_popup(e.x, e.y, "BLOCK", {0,0,1}) end
	local is_crit = math.random(100) < player.crit; local dmg = (is_crit and amt*2 or amt) * player.curse * (1 + combo/100)
	e.hp = e.hp - dmg; e.flash = 0.1; e.squash = 0.6
	play_snd(is_crit and "CRIT" or "HIT")
	dps_counter = dps_counter + dmg
	-- Damage Gradient
	local col = {1,1,1}
	if dmg > 10 then col={1,1,0} end
	if dmg > 50 then col={1,0,0} end
	
	add_popup(e.x, e.y-10, math.floor(dmg), col, is_crit and 3 or 2)
	if is_crit then shake = 2 end
end

function kill_enemy(idx)
	local e = enemies[idx]
	kills = kills + 1; combo = combo + 1; combo_timer = 2.0
	
	if e.type == "SPLITTER" then
		for k=1,2 do 
			local hp = (e.max_hp or 4)/2
			table.insert(enemies, {x=e.x+math.random(-10,10), y=e.y+math.random(-10,10), hp=hp, max_hp=hp, speed=e.speed*1.2, type="SWARMER", flash=0, shield=false, boss=false, elite=false, squash=1}) 
		end
	end
	
	if math.random(100) < player.lifesteal then player.hp = math.min(player.max_hp, player.hp + 1); add_popup(player.x, player.y, "+1", {0,1,0}) end
	
	table.insert(splats, {x=e.x, y=e.y, life=10})
	local val = (e.boss and 25 or 5)
	table.insert(gems, {x=e.x, y=e.y, val=val, col={0,1,1}, sz=8})
	-- Gold drop
	if math.random(100) <= 20 * player.greed then
		table.insert(gems, {x=e.x+5, y=e.y, val=0, gold=true, col={1,1,0}, sz=6}) -- Gold treated as gem
	end
	
	if e.boss then
		for k=1,20 do spawn_particle(e.x, e.y, {math.random(), math.random(), math.random()}) end
		if time > 600 then state = "WIN" end
		table.insert(pickups, {x=e.x, y=e.y, type="CHEST"})
	end
	
	if math.random(100) <= player.luck*2 then
		local r = math.random(100); local t="MEDKIT"
		if r>95 then t="NUKE" elseif r>90 then t="VACUUM" elseif r>85 then t="FREEZE" elseif r>80 then t="CHILLI" elseif r>75 then t="MAGNET" end
		table.insert(pickups, {x=e.x, y=e.y, type=t})
	end
	table.remove(enemies, idx)
end

function take_damage(amt, source)
	if player.i_frames > 0 then return end
	if source then killer_name = source.type end
	
	local dmg = math.max(1, amt-player.armor)
	if player.shield > 0 then player.shield = math.max(0, player.shield-dmg)
	else 
		player.hp = player.hp - dmg
		if player.hp<=0 then 
			if player.revive > 0 then player.revive=player.revive-1; player.hp=player.max_hp; enemies={}; add_popup(player.x, player.y, "REVIVED!", {1,1,0}, 4)
			else state="GAMEOVER" end
		end 
	end
	-- Damage Reflection
	if source and source.hp then damage_enemy(source, 5, "REFLECT") end
	
	player.i_frames = 0.5; shake = 15; spawn_particle(player.x, player.y, {1,0,0})
	add_popup(player.x, player.y, "-"..dmg, {1,0,0}, 3)
	play_snd("HIT")
end

function glua.event.on_keydown(k)
	if state=="PLAY" and k=="p" then state="PAUSE"
	elseif state=="PAUSE" and k=="p" then state="PLAY"
	elseif state=="LEVELUP" then
		if k=="1" then apply_perk(1)
		elseif k=="2" then apply_perk(2)
		elseif k=="3" then apply_perk(3)
		elseif k=="r" and player.gold >= player.reroll_cost then 
			player.gold = player.gold - player.reroll_cost; player.reroll_cost = player.reroll_cost + 5; generate_perks() 
		end
	end
	if k=="space" and state=="PLAY" and player.dash_cd<=0 then
		player.dash_timer=0.2; player.dash_cd=1.2; player.i_frames=0.3
		play_snd("DASH")
	end
	if k=="q" then glua.quit() end
	if k=="t" then auto_aim = not auto_aim end
	if k=="\\" and player.active_cd <= 0 then
		player.hp = math.min(player.max_hp, player.hp + 20)
		add_popup(player.x, player.y, "HEAL!", {0,1,0}, 3); player.active_cd = player.active_max; slow_mo_timer = 3.0
	end
end

-- ==========================================
-- 5. RENDER
-- ==========================================
function glua.draw(dt)
	update(dt)
	
	if weather.flash > 0 then glua.graphics.set_color(1,1,1,weather.flash); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}}); return end
	
	if state == "INTRO" then
		glua.graphics.set_color(0,0,0,1); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		local p = intro_timer / 2.0; draw_text("GLUA SURVIVORS", 200, 250 - p*100, 5, 1, 1, 1, 1-p)
		draw_text("PRESS H FOR HARD MODE", 250, 400, 2, 1, 0, 0, 1-p)
		return
	end
	
	local dv = (day_cycle + 1) / 2
	local bg = {0.05 + 0.1*dv, 0.05 + 0.05*dv, 0.1 - 0.05*dv}
	if blood_moon then bg = {0.2, 0, 0} elseif weather.type == "RAIN" then bg={0.04, 0.04, 0.06} elseif weather.type == "STORM" then bg={0.02, 0.02, 0.03} end
	glua.graphics.set_color(bg[1], bg[2], bg[3], 1); glua.graphics.clear()
	
	local pulse = 0.1 + math.sin(time*4)*0.02
	glua.graphics.set_color(pulse, pulse, pulse, 1)
	for i=0, 9 do glua.graphics.fill_rects({{0, i*100-cam_y%100, WIDTH, 2}, {i*100-cam_x%100, 0, 2, HEIGHT}}) end
	
	if math.abs(player.x) > 2000 or math.abs(player.y) > 2000 then
		glua.graphics.set_color(1,0,1,0.2 + math.random()*0.1); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		if math.random(10)==1 then draw_text("VOID", math.random(WIDTH), math.random(HEIGHT), 5, 1, 0, 1) end
	end
	
	local cx_start, cy_start = math.floor(cam_x/CELL_SIZE), math.floor(cam_y/CELL_SIZE)
	local cx_end, cy_end = cx_start + WIDTH/CELL_SIZE + 1, cy_start + HEIGHT/CELL_SIZE + 1
	
	local bases, tops = {}, {}
	
	for cx = cx_start, cx_end do for cy = cy_start, cy_end do
		local t = get_env_at(cx, cy)
		local x, y = cx*CELL_SIZE, cy*CELL_SIZE
		if t == "TREE" then
			glua.graphics.set_color(0,0,0,0.3); glua.graphics.fill_rects({{x-cam_x+10, y-cam_y+10, 40, 40}})
			table.insert(bases, {x=x+25, y=y+30, w=10, h=30, c={0.4, 0.2, 0}})
			local sway = math.sin(time*2 + cx)*5
			table.insert(tops, {x=x+10+sway, y=y+10, w=40, h=40, c={0, 0.6, 0, 0.9}})
		elseif t == "ROCK" then
			glua.graphics.set_color(0,0,0,0.3); glua.graphics.fill_rects({{x-cam_x+15, y-cam_y+25, 30, 20}})
			table.insert(bases, {x=x+15, y=y+20, w=30, h=25, c={0.5, 0.5, 0.5}})
		elseif t == "CRATE" and not destroyed_crates[cx..","..cy] then
			table.insert(bases, {x=x+10, y=y+10, w=40, h=40, c={0.6, 0.4, 0.2}})
			table.insert(tops, {x=x+15, y=y+15, w=30, h=30, c={0.7, 0.5, 0.3}})
		elseif t == "BARREL" and not destroyed_crates[cx..","..cy] then
			table.insert(bases, {x=x+15, y=y+15, w=30, h=40, c={1, 0, 0}})
		elseif t == "NEST" then
			table.insert(bases, {x=x+5, y=y+5, w=50, h=50, c={0.4, 0, 0.4}})
		elseif t == "SHRINE" and not destroyed_crates[cx..","..cy] then
			table.insert(bases, {x=x+20, y=y, w=20, h=60, c={1, 0, 0}})
		elseif t == "WATER" then
			table.insert(bases, {x=x, y=y, w=CELL_SIZE, h=CELL_SIZE, c={0, 0.4, 0.8, 0.6}})
		elseif t == "LAVA" then
			table.insert(bases, {x=x, y=y, w=CELL_SIZE, h=CELL_SIZE, c={0.8, 0.2, 0, 0.8}})
		elseif t == "ICE" then
			table.insert(bases, {x=x, y=y, w=CELL_SIZE, h=CELL_SIZE, c={0.8, 1, 1, 0.6}})
		elseif t == "GRASS" then
			local sway = math.sin(time*3 + cx*cy)*3
			table.insert(bases, {x=x+25+sway, y=y+25, w=6, h=6, c={0, 0.8, 0.2, 0.5}})
		end
	end end
	
	for _,b in ipairs(bases) do local c=b.c; glua.graphics.set_color(c[1],c[2],c[3],c[4] or 1); glua.graphics.fill_rects({{b.x-cam_x, b.y-cam_y, b.w, b.h}}) end
	
	for i=#footprints,1,-1 do local f=footprints[i]; f.life=f.life-dt; glua.graphics.set_color(0,0,0,f.life/4); glua.graphics.fill_rects({{f.x-cam_x, f.y-cam_y, 4, 4}}); if f.life<0 then table.remove(footprints,i) end end
	for i=#splats,1,-1 do local s=splats[i]; glua.graphics.set_color(0.4, 0, 0, s.life/10); glua.graphics.fill_rects({{s.x-cam_x, s.y-cam_y, 20, 20}}) end
	for _,m in ipairs(mines) do 
		if m.enemy then glua.graphics.set_color(0,1,0,0.8) else glua.graphics.set_color(0.8,0.4,0,1) end
		glua.graphics.fill_rects({{m.x-cam_x, m.y-cam_y, 14, 14}}) 
	end
	for _,g in ipairs(gems) do 
		if g.gold then glua.graphics.set_color(1,1,0,1) else glua.graphics.set_color(g.col[1],g.col[2],g.col[3],1) end
		glua.graphics.fill_rects({{g.x-cam_x, g.y-cam_y, g.sz, g.sz}}) 
	end
	for _,p in ipairs(pickups) do
		local c = {1,1,1}; if p.type=="MEDKIT" then c={1,0,0} elseif p.type=="NUKE" then c={1,0.5,0} elseif p.type=="VACUUM" then c={1,0,1} elseif p.type=="MERCHANT" then c={1,1,0} end
		glua.graphics.set_color(c[1],c[2],c[3],1); glua.graphics.fill_rects({{p.x-cam_x, p.y-cam_y, 16, 16}})
	end
	
	for _,bh in ipairs(blackholes) do glua.graphics.set_color(0,0,0,1); glua.graphics.fill_rects({{bh.x-cam_x-20, bh.y-cam_y-20, 40, 40}}) end
	for _,m in ipairs(meteors) do glua.graphics.set_color(1,0,0,0.3); glua.graphics.fill_rects({{m.x-cam_x-40, m.y-cam_y-40, 80, 80}}) end

	-- Garlic Aura
	if player.garlic then glua.graphics.set_color(1,1,1,0.1); glua.graphics.fill_rects({{player.x-cam_x-80, player.y-cam_y-80, 160, 160}}) end

	for _,e in ipairs(enemies) do
		if e.type ~= "INVISIBLE" or dist(e.x,e.y,player.x,player.y) < 100 then
			local sz = (e.boss and 60 or 24) * (e.squash or 1)
			glua.graphics.set_color(0,0,0,0.4); glua.graphics.fill_rects({{e.x-cam_x+4, e.y-cam_y+4, sz, sz}})
			if e.flash>0 then glua.graphics.set_color(1,1,1,1)
			elseif e.type=="BOMBER" then glua.graphics.set_color(1, 0.5, 0, 1)
			elseif e.type=="SHOOTER" then glua.graphics.set_color(0.8, 0.4, 0, 1)
			elseif e.type=="SWARMER" then glua.graphics.set_color(0.6, 0.3, 0.3, 1)
			elseif e.type=="HEALER" then glua.graphics.set_color(0, 1, 0, 1)
			elseif e.type=="SPLITTER" then glua.graphics.set_color(0.5, 0, 1, 1)
			elseif e.type=="INVISIBLE" then glua.graphics.set_color(1,1,1,0.2)
			elseif e.type=="CHARGER" then glua.graphics.set_color(0.4, 0.2, 0, 1)
			elseif e.type=="GHOST" then glua.graphics.set_color(0.8, 0.8, 1, 0.5)
			elseif e.type=="SLIME" then glua.graphics.set_color(0, 0.8, 0, 1)
			elseif e.boss then glua.graphics.set_color(0.9,0,0,1)
			else glua.graphics.set_color(0.6,0.2,0.2,1) end
			glua.graphics.fill_rects({{e.x-cam_x, e.y-cam_y, sz, sz}})
			
			if e.shield then glua.graphics.set_color(0,0.5,1,1); glua.graphics.fill_rects({{e.x-cam_x-2, e.y-cam_y-2, sz+4, sz+4}}) end
			local mhp = e.max_hp or e.hp or 1
			if e.hp < mhp then glua.graphics.set_color(1,0,0,1); glua.graphics.fill_rects({{e.x-cam_x, e.y-cam_y-5, sz*(e.hp/mhp), 3}}) end
			if e.elite then glua.graphics.set_color(1,1,0,1); glua.graphics.fill_rects({{e.x-cam_x+sz/2-2, e.y-cam_y-8, 4, 4}}) end -- Yellow Health Bar for Elite
			
			-- Turret Laser
			if (e.type=="SHOOTER" or e.type=="TURRET") and dist(e.x,e.y,player.x,player.y)<500 then
				glua.graphics.set_color(1,0,0,0.3); local dx, dy = player.x-e.x, player.y-e.y
				glua.graphics.fill_rects({{e.x-cam_x, e.y-cam_y, dx, 1}, {e.x-cam_x, e.y-cam_y, 1, dy}})
			end
		end
	end
	
	if player.i_frames<=0 or math.floor(time*15)%2==0 then
		glua.graphics.set_color(0,0,0,0.4); glua.graphics.fill_rects({{player.x-cam_x+4, player.y-cam_y+4, 24, 24}})
		glua.graphics.set_color(1,1,1,1); glua.graphics.fill_rects({{player.x-cam_x, player.y-cam_y, 24, 24}})
		glua.graphics.set_color(0,0,0,1); glua.graphics.fill_rects({{player.x-cam_x+8+player.facing_x*4, player.y-cam_y+8, 4, 4}, {player.x-cam_x+16+player.facing_x*4, player.y-cam_y+8, 4, 4}})
		if player.orb_shield then glua.graphics.set_color(0,1,1,0.5); glua.graphics.fill_rects({{player.x-cam_x-10, player.y-cam_y-10, 44, 44}}) end
		-- Active Item Ring
		local ap = 1 - (player.active_cd / player.active_max)
		if ap > 0 then glua.graphics.set_color(0,1,0,0.3); glua.graphics.fill_rects({{player.x-cam_x-2, player.y-cam_y+26, 28*ap, 2}}) end
	end
	
	for _,a in ipairs(afterimages) do glua.graphics.set_color(1,1,1,a.life); glua.graphics.fill_rects({{a.x-cam_x, a.y-cam_y, 24, 24}}) end
	for _,t in ipairs(tops) do 
		local c=t.c; local alpha = c[4] or 1
		-- Tree Transparency
		if dist(player.x, player.y, t.x+20, t.y+20) < 60 then alpha = 0.4 end
		glua.graphics.set_color(c[1],c[2],c[3],alpha); glua.graphics.fill_rects({{t.x-cam_x, t.y-cam_y, t.w, t.h}}) 
	end

	for _,b in ipairs(bullets) do
		local col = {1,1,0,1}
		if b.type=="AXE" then col={0.8,0.8,1,1}
		elseif b.type=="POISON" then col={0,1,0,0.5}
		elseif b.type=="FLAME" then col={1,0.5,0,0.7}
		elseif b.type=="MISSILE" then col={1,0,0,1}
		elseif b.type=="PETLASER" then col={1,0,1,1} 
		elseif b.type=="DAGGER" then col={0.8,0.8,0.8,1} end
		glua.graphics.set_color(col[1],col[2],col[3],col[4])
		local sz = (b.type=="POISON" and 40 or 10)
		glua.graphics.fill_rects({{b.x-cam_x, b.y-cam_y, sz, sz}})
	end
	glua.graphics.set_color(1,0,0,1); for _,b in ipairs(enemy_bullets) do glua.graphics.fill_rects({{b.x-cam_x, b.y-cam_y, 12, 12}}) end
	
	if player.saws > 0 then
		glua.graphics.set_color(0.9, 0.9, 0.9, 1)
		for i=1, player.saws do
			local a = (time * 3) + (i * (6.28/player.saws)); local sx, sy = player.x + math.cos(a)*70*player.area, player.y + math.sin(a)*70*player.area
			glua.graphics.fill_rects({{sx-cam_x, sy-cam_y, 16*player.area, 16*player.area}})
		end
	end

	if weather.type == "RAIN" or weather.type == "STORM" then
		if #env_bolts > 0 then
			glua.graphics.set_color(0.8, 0.9, 1.0, 0.5)
			for _, b in ipairs(env_bolts) do for _, s in ipairs(b.segs) do
				local len = math.max(1, math.abs(s.y2 - s.y1)); glua.graphics.fill_rects({{s.x1, s.y1, 2, len}, {s.x1, s.y2, s.x2-s.x1, 2}})
			end end
		end
		glua.graphics.set_color(0.6, 0.6, 1, 0.3)
		local rr = {}; local speed = (weather.type=="STORM" and 25 or 15); local slant = (weather.type=="STORM" and 5 or 2)
		for i, r in ipairs(rain_drops) do
			r.y = (r.y + speed) % HEIGHT; r.x = (r.x - slant) % WIDTH; table.insert(rr, {r.x, r.y, 2, r.s})
		end
		glua.graphics.fill_rects(rr)
		glua.graphics.set_color(0,0,0, weather.type=="STORM" and 0.4 or 0.2); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		-- Splashes
		glua.graphics.set_color(0.7,0.7,1,0.5)
		for _,s in ipairs(weather.splash) do glua.graphics.fill_rects({{s.x, s.y-5, 4, 2}}) end
	end
	
	for _,s in ipairs(shockwaves) do glua.graphics.set_color(1,1,1,s.life); glua.graphics.fill_rects({{s.x-cam_x-s.r, s.y-cam_y-s.r, s.r*2, s.r*2}}) end

	for _,p in ipairs(popups) do draw_text(p.txt, p.x-cam_x, p.y-cam_y, p.size, p.col[1], p.col[2], p.col[3], p.life/p.max_life) end
	if tutorial_alpha > 0 then draw_text("WASD MOVE / SPACE DASH", 150, 400, 3, 1, 1, 1, tutorial_alpha/5) end

	glua.graphics.set_color(0,0,0,0.4); glua.graphics.fill_rects({{0,0,WIDTH,10},{0,HEIGHT-10,WIDTH,10},{0,0,10,HEIGHT},{WIDTH-10,0,10,HEIGHT}})
	if player.hp < player.max_hp*0.2 then glua.graphics.set_color(1,0,0,0.2 + math.sin(time*10)*0.1); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}}) end

	glua.graphics.set_color(0,0,0,0.8); glua.graphics.fill_rects({{WIDTH/2-102, HEIGHT-32, 204, 24}})
	glua.graphics.set_color(1,0,0,1); glua.graphics.fill_rects({{WIDTH/2-100, HEIGHT-30, 200*(player.hp/player.max_hp), 20}})
	if player.shield > 0 then glua.graphics.set_color(0.3,0.6,1,0.6); glua.graphics.fill_rects({{WIDTH/2-100, HEIGHT-30, 200*(player.shield/player.max_shield), 20}}) end
	glua.graphics.set_color(0,0.5,1,1); glua.graphics.fill_rects({{0,0,WIDTH*(player.exp/FIXED_XP), 8}})
	
	glua.graphics.set_color(1,1,0,1); glua.graphics.fill_rects({{WIDTH/2-50, HEIGHT-50, 100*(1-(player.dash_cd/1.2)), 4}})
	glua.graphics.set_color(0,1,0,1); glua.graphics.fill_rects({{WIDTH/2-50, HEIGHT-60, 100*(1-(player.active_cd/player.active_max)), 4}})

	draw_text("LVL "..player.lvl, 10, 15, 3)
	draw_text("GOLD "..player.gold, 10, 45, 3, 1, 1, 0)
	draw_text("DPS "..dps_counter, 10, 75, 2)
	draw_text(weather.type, WIDTH-160, 15, 3)
	draw_text("FPS "..math.floor(1/dt), WIDTH-160, 45, 2)
	draw_text("AIM: "..(auto_aim and "AUTO" or "MANUAL"), WIDTH-160, 75, 2)
	if combo > 5 then draw_text(combo.." COMBO", WIDTH-220, 100, 3, 1, 0.5, 0, combo_timer/2.0) end
	draw_text("TIME "..math.floor(time), WIDTH/2-60, 15, 3)
	
	for _, e in ipairs(enemies) do if e.boss then
		glua.graphics.set_color(0,0,0,0.8); glua.graphics.fill_rects({{200, 50, 400, 20}})
		glua.graphics.set_color(1,0,0,1); glua.graphics.fill_rects({{200, 50, 400*(e.hp/e.max_hp), 20}})
		draw_text("BOSS", 370, 30, 2, 1, 0, 0)
	end end

	local mx, my, ms = WIDTH-110, HEIGHT-110, 100
	glua.graphics.set_color(0,0,0,0.7); glua.graphics.fill_rects({{mx, my, ms, ms}})
	glua.graphics.set_color(0,1,1,1); glua.graphics.fill_rects({{mx+ms/2-2, my+ms/2-2, 4, 4}})
	local mr = {}
	for _, e in ipairs(enemies) do
		local ex, ey = (e.x-player.x)/20, (e.y-player.y)/20
		if math.abs(ex)<ms/2 and math.abs(ey)<ms/2 then table.insert(mr, {mx+ms/2+ex, my+ms/2+ey, 3, 3}) end
	end
	glua.graphics.set_color(1,0,0,0.8); glua.graphics.fill_rects(mr)

	if state=="LEVELUP" then
		glua.graphics.set_color(0,0,0,0.85); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		local scale = 1 + math.sin(time*5)*0.1
		draw_text("LEVEL UP", 320 - (scale*10), 120, 4*scale, 1,1,0)
		draw_text("R TO REROLL ("..player.reroll_cost.."G)", 300, 450, 2, 1, 1, 0)
		for i,p in ipairs(perks) do
			local c = p.c
			draw_text(i..". "..p.n.." ("..p.r..")", 150, 200+i*60, 3, c[1], c[2], c[3])
		end
	elseif state=="PAUSE" then
		glua.graphics.set_color(0,0,0,0.7); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		draw_text("PAUSED", 330, 280, 4)
	elseif state=="WIN" then
		glua.graphics.set_color(1,1,1,1); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		draw_text("VICTORY!", 280, 250, 5, 0,0,0)
	elseif state=="GAMEOVER" then
		glua.graphics.set_color(0,0,0,1); glua.graphics.fill_rects({{0,0,WIDTH,HEIGHT}})
		draw_text("GAME OVER", 280, 250, 5, 1,0,0)
		if killer_name ~= "" then draw_text("KILLED BY: "..killer_name, 300, 350, 2, 1, 1, 1) end
	end
end
